### ISSUE TITLE
Choose a License

### ISSUE THREAD

**Issue by beyarkay** [StuartMesham/not-vegetable#1]
Need to decide on [which license](https://choosealicense.com) we [need to use](https://www.infoworld.com/article/2839560/sticking-a-license-on-everything.html)

Personally I'm all for the GNU GPLv3. It lets people do almost anything they want with our project, except distribute closed source versions. Basically it's free to use, as long as they make their version free to use as well.

**Comment by StuartMesham** [comment]
Agreed. GNU GPLv3 it is.
