### ISSUE TITLE
Create a SQL-style Query tool

### ISSUE THREAD

**Issue by beyarkay** [StuartMesham/not-vegetable#3]
Build a tool that takes in a SQL style request, and returns all the images / image urls that satisfy that request. For example, the tool should make it easy to
* Get all fruit / vegetables
* Get all legumes and strawberries
* Get the first 10 strawberries
* Chose 10 random strawberries
* Get 10 images from every category of fruit / vegetable
* etc

**Comment by StuartMesham** [comment]
Done.
