### ISSUE TITLE
Create / Find a Quick Image labeller tool

### ISSUE THREAD

**Issue by beyarkay** [StuartMesham/not-vegetable#5]
Create an interface that allows us to quickly assign labels to lots of images. I was thinking a Tinder style interface:
* You're shown a photo
* You press a button (say a number from 1 to 4)
* The program labels the image and immediately shows you the next one
* Repeat

**Comment by StuartMesham** [comment]
I don't think we need to manually label any images at the moment since we have the wnids for all of the URLs, but if we do need to at some point then here are two to look at:

https://github.com/lzx1413/LabelImgTool (CLS mode)
https://github.com/Nestak2/image-sorter2

**Comment by StuartMesham** [comment]
I think this is also a non-issue for now. We can re-open this later if need be.
