### ISSUE TITLE
Clean the Data

### ISSUE THREAD

**Issue by beyarkay** [StuartMesham/not-vegetable#7]
So this is a big one, might find that it's best to split it into multiple issues:
1. Create a new directory as a backup of all the image urls
2. Create a new directory that only contains the urls we actually want to use
     * Remove all image urls that don't actually lead to an images
     * Remove all image urls with more than one type of fruit / veg in it
     * Create a script that will re-clean our data, in case we add more images / some of the urls become invalid

**Comment by StuartMesham** [comment]
Since Aria2 doesn't seem to dwell on the broken links for too long I think this is a non-issue for now. We can re-open this later if we decide we want it.
