### ISSUE TITLE
remove list_project_structure.py

### ISSUE THREAD

**Issue by StuartMesham** [StuartMesham/not-vegetable#9]
I think we can do without this script by running `tree --filelimit 20` from the project root instead. I also think it's output is more readable than the python script's output.

**Comment by beyarkay** [comment]
I'm very open to a better / more readable version, could you implement the `tree --filelimit 20` code?

**Comment by beyarkay** [comment]
Also, I wonder if @luc_hayward gets an email notification for every message?

**Comment by StuartMesham** [comment]
He must be getting so much FOMO if he does.
